import Header from "@/components/Layout/Header";
import ReduxLayout from "@/components/Layout/ReduxLayout";
import ThemeLayout from "@/components/Layout/ThemeLayout";
import UseQueryWrap from "@/components/Layout/UseQueryWrap";
import "./globals.scss";
export const metadata = {
  title: "OOP SEARCH",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeLayout>
          <ReduxLayout>
            <UseQueryWrap>
              <Header />
              {children}
            </UseQueryWrap>
          </ReduxLayout>
        </ThemeLayout>
      </body>
    </html>
  );
}
